module Puzzle
  module ErrorCode
    PARAM_ERROR = "PARAM_ERROR"
    LOGIN_FAIL = "LOGIN_FAIL"
    TOKEN_FAIL = "TOKEN_FAIL"
    PURCHASE_LOW_POINTS = "PURCHASE_LOW_POINTS"
    CONTACT_NOT_EXIST = "CONTACT_NOT_EXIS"
    CONTACT_NOT_OWNED = "CONTACT_NOT_OWNED"
    SEARCH_ERROR = "SEARCH_ERROR"
    SYS_ERROR = "SYS_ERROR"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    NOT_AVAILABLE = "NOT_AVAILABLE"
  end
end
